name: Build the darn thing

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, experiments/* ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-on-mac:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install raylib
          brew install catch2

      - name: Build it
        run: make
        working-directory: ./src

      - name: Check it
        run: make check
        working-directory: ./src
